import SideBar from '@/components/SideBar';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Social Media App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<div className="flex flex-row min-h-screen min-w-screen  bg-black overflow-hidden">
					<SideBar />
					{children}
				</div>
			</body>
		</html>
	);
}
